/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentInviteRouteImport } from './routes/student-invite'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBudgetAnalysisRouteImport } from './routes/_authenticated/budget-analysis'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCustomizationsRouteImport } from './routes/_authenticated/customizations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAtelierAttendanceRouteImport } from './routes/_authenticated/atelier.attendance'
import { Route as AuthenticatedAtelierCashFlowRouteImport } from './routes/_authenticated/atelier.cash-flow'
import { Route as AuthenticatedAtelierClassMaterialsRouteImport } from './routes/_authenticated/atelier.class-materials'
import { Route as AuthenticatedAtelierFiringPricingRouteImport } from './routes/_authenticated/atelier.firing-pricing'
import { Route as AuthenticatedAtelierKilnsRouteImport } from './routes/_authenticated/atelier.kilns'
import { Route as AuthenticatedAtelierPiecePricingRouteImport } from './routes/_authenticated/atelier.piece-pricing'
import { Route as AuthenticatedAtelierRawMaterialsRouteImport } from './routes/_authenticated/atelier.raw-materials'
import { Route as AuthenticatedAtelierRenovationRouteImport } from './routes/_authenticated/atelier.renovation'
import { Route as AuthenticatedAtelierStudentPaymentsRouteImport } from './routes/_authenticated/atelier.student-payments'
import { Route as AuthenticatedAtelierStudentsRouteImport } from './routes/_authenticated/atelier.students'
import { Route as AuthenticatedAtelierWorkshopPricingRouteImport } from './routes/_authenticated/atelier.workshop-pricing'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedStudentAccountRouteImport } from './routes/_authenticated/student.account'
import { Route as AuthenticatedStudentClassesRouteImport } from './routes/_authenticated/student.classes'
import { Route as AuthenticatedStudentPaymentsRouteImport } from './routes/_authenticated/student.payments'
import { Route as AuthenticatedStudentPiecesRouteImport } from './routes/_authenticated/student.pieces'
import { Route as AuthenticatedStudentProjectsRouteImport } from './routes/_authenticated/student.projects'
import { Route as AuthenticatedSuperAdminCustomizationsRouteImport } from './routes/_authenticated/super-admin.customizations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentInviteRoute = StudentInviteRouteImport.update({
  id: '/student-invite',
  path: '/student-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetAnalysisRoute =
  AuthenticatedBudgetAnalysisRouteImport.update({
    id: '/budget-analysis',
    path: '/budget-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomizationsRoute =
  AuthenticatedCustomizationsRouteImport.update({
    id: '/customizations',
    path: '/customizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAtelierAttendanceRoute =
  AuthenticatedAtelierAttendanceRouteImport.update({
    id: '/atelier/attendance',
    path: '/atelier/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierCashFlowRoute =
  AuthenticatedAtelierCashFlowRouteImport.update({
    id: '/atelier/cash-flow',
    path: '/atelier/cash-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierClassMaterialsRoute =
  AuthenticatedAtelierClassMaterialsRouteImport.update({
    id: '/atelier/class-materials',
    path: '/atelier/class-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierFiringPricingRoute =
  AuthenticatedAtelierFiringPricingRouteImport.update({
    id: '/atelier/firing-pricing',
    path: '/atelier/firing-pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierKilnsRoute =
  AuthenticatedAtelierKilnsRouteImport.update({
    id: '/atelier/kilns',
    path: '/atelier/kilns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierPiecePricingRoute =
  AuthenticatedAtelierPiecePricingRouteImport.update({
    id: '/atelier/piece-pricing',
    path: '/atelier/piece-pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierRawMaterialsRoute =
  AuthenticatedAtelierRawMaterialsRouteImport.update({
    id: '/atelier/raw-materials',
    path: '/atelier/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierRenovationRoute =
  AuthenticatedAtelierRenovationRouteImport.update({
    id: '/atelier/renovation',
    path: '/atelier/renovation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierStudentPaymentsRoute =
  AuthenticatedAtelierStudentPaymentsRouteImport.update({
    id: '/atelier/student-payments',
    path: '/atelier/student-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierStudentsRoute =
  AuthenticatedAtelierStudentsRouteImport.update({
    id: '/atelier/students',
    path: '/atelier/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierWorkshopPricingRoute =
  AuthenticatedAtelierWorkshopPricingRouteImport.update({
    id: '/atelier/workshop-pricing',
    path: '/atelier/workshop-pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAccountRoute =
  AuthenticatedStudentAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentClassesRoute =
  AuthenticatedStudentClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentPaymentsRoute =
  AuthenticatedStudentPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentPiecesRoute =
  AuthenticatedStudentPiecesRouteImport.update({
    id: '/pieces',
    path: '/pieces',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProjectsRoute =
  AuthenticatedStudentProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedSuperAdminCustomizationsRoute =
  AuthenticatedSuperAdminCustomizationsRouteImport.update({
    id: '/super-admin/customizations',
    path: '/super-admin/customizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/student-invite': typeof StudentInviteRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customizations': typeof AuthenticatedCustomizationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atelier/attendance': typeof AuthenticatedAtelierAttendanceRoute
  '/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/atelier/firing-pricing': typeof AuthenticatedAtelierFiringPricingRoute
  '/atelier/kilns': typeof AuthenticatedAtelierKilnsRoute
  '/atelier/piece-pricing': typeof AuthenticatedAtelierPiecePricingRoute
  '/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/atelier/renovation': typeof AuthenticatedAtelierRenovationRoute
  '/atelier/student-payments': typeof AuthenticatedAtelierStudentPaymentsRoute
  '/atelier/students': typeof AuthenticatedAtelierStudentsRoute
  '/atelier/workshop-pricing': typeof AuthenticatedAtelierWorkshopPricingRoute
  '/student/account': typeof AuthenticatedStudentAccountRoute
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/student/payments': typeof AuthenticatedStudentPaymentsRoute
  '/student/pieces': typeof AuthenticatedStudentPiecesRoute
  '/student/projects': typeof AuthenticatedStudentProjectsRoute
  '/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/student-invite': typeof StudentInviteRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customizations': typeof AuthenticatedCustomizationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atelier/attendance': typeof AuthenticatedAtelierAttendanceRoute
  '/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/atelier/firing-pricing': typeof AuthenticatedAtelierFiringPricingRoute
  '/atelier/kilns': typeof AuthenticatedAtelierKilnsRoute
  '/atelier/piece-pricing': typeof AuthenticatedAtelierPiecePricingRoute
  '/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/atelier/renovation': typeof AuthenticatedAtelierRenovationRoute
  '/atelier/student-payments': typeof AuthenticatedAtelierStudentPaymentsRoute
  '/atelier/students': typeof AuthenticatedAtelierStudentsRoute
  '/atelier/workshop-pricing': typeof AuthenticatedAtelierWorkshopPricingRoute
  '/student/account': typeof AuthenticatedStudentAccountRoute
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/student/payments': typeof AuthenticatedStudentPaymentsRoute
  '/student/pieces': typeof AuthenticatedStudentPiecesRoute
  '/student/projects': typeof AuthenticatedStudentProjectsRoute
  '/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
  '/student': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/student-invite': typeof StudentInviteRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customizations': typeof AuthenticatedCustomizationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/atelier/attendance': typeof AuthenticatedAtelierAttendanceRoute
  '/_authenticated/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/_authenticated/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/_authenticated/atelier/firing-pricing': typeof AuthenticatedAtelierFiringPricingRoute
  '/_authenticated/atelier/kilns': typeof AuthenticatedAtelierKilnsRoute
  '/_authenticated/atelier/piece-pricing': typeof AuthenticatedAtelierPiecePricingRoute
  '/_authenticated/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/_authenticated/atelier/renovation': typeof AuthenticatedAtelierRenovationRoute
  '/_authenticated/atelier/student-payments': typeof AuthenticatedAtelierStudentPaymentsRoute
  '/_authenticated/atelier/students': typeof AuthenticatedAtelierStudentsRoute
  '/_authenticated/atelier/workshop-pricing': typeof AuthenticatedAtelierWorkshopPricingRoute
  '/_authenticated/student/account': typeof AuthenticatedStudentAccountRoute
  '/_authenticated/student/classes': typeof AuthenticatedStudentClassesRoute
  '/_authenticated/student/payments': typeof AuthenticatedStudentPaymentsRoute
  '/_authenticated/student/pieces': typeof AuthenticatedStudentPiecesRoute
  '/_authenticated/student/projects': typeof AuthenticatedStudentProjectsRoute
  '/_authenticated/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/student-invite'
    | '/accounts'
    | '/billing'
    | '/budget-analysis'
    | '/cards'
    | '/categories'
    | '/customizations'
    | '/dashboard'
    | '/feedback'
    | '/import'
    | '/onboarding'
    | '/reconciliation'
    | '/settings'
    | '/student'
    | '/transactions'
    | '/auth/callback'
    | '/atelier/attendance'
    | '/atelier/cash-flow'
    | '/atelier/class-materials'
    | '/atelier/firing-pricing'
    | '/atelier/kilns'
    | '/atelier/piece-pricing'
    | '/atelier/raw-materials'
    | '/atelier/renovation'
    | '/atelier/student-payments'
    | '/atelier/students'
    | '/atelier/workshop-pricing'
    | '/student/account'
    | '/student/classes'
    | '/student/payments'
    | '/student/pieces'
    | '/student/projects'
    | '/super-admin/customizations'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/student-invite'
    | '/accounts'
    | '/billing'
    | '/budget-analysis'
    | '/cards'
    | '/categories'
    | '/customizations'
    | '/dashboard'
    | '/feedback'
    | '/import'
    | '/onboarding'
    | '/reconciliation'
    | '/settings'
    | '/transactions'
    | '/auth/callback'
    | '/atelier/attendance'
    | '/atelier/cash-flow'
    | '/atelier/class-materials'
    | '/atelier/firing-pricing'
    | '/atelier/kilns'
    | '/atelier/piece-pricing'
    | '/atelier/raw-materials'
    | '/atelier/renovation'
    | '/atelier/student-payments'
    | '/atelier/students'
    | '/atelier/workshop-pricing'
    | '/student/account'
    | '/student/classes'
    | '/student/payments'
    | '/student/pieces'
    | '/student/projects'
    | '/super-admin/customizations'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/student-invite'
    | '/_authenticated/accounts'
    | '/_authenticated/billing'
    | '/_authenticated/budget-analysis'
    | '/_authenticated/cards'
    | '/_authenticated/categories'
    | '/_authenticated/customizations'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/import'
    | '/_authenticated/onboarding'
    | '/_authenticated/reconciliation'
    | '/_authenticated/settings'
    | '/_authenticated/student'
    | '/_authenticated/transactions'
    | '/auth/callback'
    | '/_authenticated/atelier/attendance'
    | '/_authenticated/atelier/cash-flow'
    | '/_authenticated/atelier/class-materials'
    | '/_authenticated/atelier/firing-pricing'
    | '/_authenticated/atelier/kilns'
    | '/_authenticated/atelier/piece-pricing'
    | '/_authenticated/atelier/raw-materials'
    | '/_authenticated/atelier/renovation'
    | '/_authenticated/atelier/student-payments'
    | '/_authenticated/atelier/students'
    | '/_authenticated/atelier/workshop-pricing'
    | '/_authenticated/student/account'
    | '/_authenticated/student/classes'
    | '/_authenticated/student/payments'
    | '/_authenticated/student/pieces'
    | '/_authenticated/student/projects'
    | '/_authenticated/super-admin/customizations'
    | '/_authenticated/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentInviteRoute: typeof StudentInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-invite': {
      id: '/student-invite'
      path: '/student-invite'
      fullPath: '/student-invite'
      preLoaderRoute: typeof StudentInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget-analysis': {
      id: '/_authenticated/budget-analysis'
      path: '/budget-analysis'
      fullPath: '/budget-analysis'
      preLoaderRoute: typeof AuthenticatedBudgetAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customizations': {
      id: '/_authenticated/customizations'
      path: '/customizations'
      fullPath: '/customizations'
      preLoaderRoute: typeof AuthenticatedCustomizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/atelier/attendance': {
      id: '/_authenticated/atelier/attendance'
      path: '/atelier/attendance'
      fullPath: '/atelier/attendance'
      preLoaderRoute: typeof AuthenticatedAtelierAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/cash-flow': {
      id: '/_authenticated/atelier/cash-flow'
      path: '/atelier/cash-flow'
      fullPath: '/atelier/cash-flow'
      preLoaderRoute: typeof AuthenticatedAtelierCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/class-materials': {
      id: '/_authenticated/atelier/class-materials'
      path: '/atelier/class-materials'
      fullPath: '/atelier/class-materials'
      preLoaderRoute: typeof AuthenticatedAtelierClassMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/firing-pricing': {
      id: '/_authenticated/atelier/firing-pricing'
      path: '/atelier/firing-pricing'
      fullPath: '/atelier/firing-pricing'
      preLoaderRoute: typeof AuthenticatedAtelierFiringPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/kilns': {
      id: '/_authenticated/atelier/kilns'
      path: '/atelier/kilns'
      fullPath: '/atelier/kilns'
      preLoaderRoute: typeof AuthenticatedAtelierKilnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/piece-pricing': {
      id: '/_authenticated/atelier/piece-pricing'
      path: '/atelier/piece-pricing'
      fullPath: '/atelier/piece-pricing'
      preLoaderRoute: typeof AuthenticatedAtelierPiecePricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/raw-materials': {
      id: '/_authenticated/atelier/raw-materials'
      path: '/atelier/raw-materials'
      fullPath: '/atelier/raw-materials'
      preLoaderRoute: typeof AuthenticatedAtelierRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/renovation': {
      id: '/_authenticated/atelier/renovation'
      path: '/atelier/renovation'
      fullPath: '/atelier/renovation'
      preLoaderRoute: typeof AuthenticatedAtelierRenovationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/student-payments': {
      id: '/_authenticated/atelier/student-payments'
      path: '/atelier/student-payments'
      fullPath: '/atelier/student-payments'
      preLoaderRoute: typeof AuthenticatedAtelierStudentPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/students': {
      id: '/_authenticated/atelier/students'
      path: '/atelier/students'
      fullPath: '/atelier/students'
      preLoaderRoute: typeof AuthenticatedAtelierStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/workshop-pricing': {
      id: '/_authenticated/atelier/workshop-pricing'
      path: '/atelier/workshop-pricing'
      fullPath: '/atelier/workshop-pricing'
      preLoaderRoute: typeof AuthenticatedAtelierWorkshopPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/account': {
      id: '/_authenticated/student/account'
      path: '/account'
      fullPath: '/student/account'
      preLoaderRoute: typeof AuthenticatedStudentAccountRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/classes': {
      id: '/_authenticated/student/classes'
      path: '/classes'
      fullPath: '/student/classes'
      preLoaderRoute: typeof AuthenticatedStudentClassesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/payments': {
      id: '/_authenticated/student/payments'
      path: '/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof AuthenticatedStudentPaymentsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/pieces': {
      id: '/_authenticated/student/pieces'
      path: '/pieces'
      fullPath: '/student/pieces'
      preLoaderRoute: typeof AuthenticatedStudentPiecesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/projects': {
      id: '/_authenticated/student/projects'
      path: '/projects'
      fullPath: '/student/projects'
      preLoaderRoute: typeof AuthenticatedStudentProjectsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/super-admin/customizations': {
      id: '/_authenticated/super-admin/customizations'
      path: '/super-admin/customizations'
      fullPath: '/super-admin/customizations'
      preLoaderRoute: typeof AuthenticatedSuperAdminCustomizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAccountRoute: typeof AuthenticatedStudentAccountRoute
  AuthenticatedStudentClassesRoute: typeof AuthenticatedStudentClassesRoute
  AuthenticatedStudentPaymentsRoute: typeof AuthenticatedStudentPaymentsRoute
  AuthenticatedStudentPiecesRoute: typeof AuthenticatedStudentPiecesRoute
  AuthenticatedStudentProjectsRoute: typeof AuthenticatedStudentProjectsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAccountRoute: AuthenticatedStudentAccountRoute,
  AuthenticatedStudentClassesRoute: AuthenticatedStudentClassesRoute,
  AuthenticatedStudentPaymentsRoute: AuthenticatedStudentPaymentsRoute,
  AuthenticatedStudentPiecesRoute: AuthenticatedStudentPiecesRoute,
  AuthenticatedStudentProjectsRoute: AuthenticatedStudentProjectsRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBudgetAnalysisRoute: typeof AuthenticatedBudgetAnalysisRoute
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomizationsRoute: typeof AuthenticatedCustomizationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedAtelierAttendanceRoute: typeof AuthenticatedAtelierAttendanceRoute
  AuthenticatedAtelierCashFlowRoute: typeof AuthenticatedAtelierCashFlowRoute
  AuthenticatedAtelierClassMaterialsRoute: typeof AuthenticatedAtelierClassMaterialsRoute
  AuthenticatedAtelierFiringPricingRoute: typeof AuthenticatedAtelierFiringPricingRoute
  AuthenticatedAtelierKilnsRoute: typeof AuthenticatedAtelierKilnsRoute
  AuthenticatedAtelierPiecePricingRoute: typeof AuthenticatedAtelierPiecePricingRoute
  AuthenticatedAtelierRawMaterialsRoute: typeof AuthenticatedAtelierRawMaterialsRoute
  AuthenticatedAtelierRenovationRoute: typeof AuthenticatedAtelierRenovationRoute
  AuthenticatedAtelierStudentPaymentsRoute: typeof AuthenticatedAtelierStudentPaymentsRoute
  AuthenticatedAtelierStudentsRoute: typeof AuthenticatedAtelierStudentsRoute
  AuthenticatedAtelierWorkshopPricingRoute: typeof AuthenticatedAtelierWorkshopPricingRoute
  AuthenticatedSuperAdminCustomizationsRoute: typeof AuthenticatedSuperAdminCustomizationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBudgetAnalysisRoute: AuthenticatedBudgetAnalysisRoute,
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomizationsRoute: AuthenticatedCustomizationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedAtelierAttendanceRoute: AuthenticatedAtelierAttendanceRoute,
  AuthenticatedAtelierCashFlowRoute: AuthenticatedAtelierCashFlowRoute,
  AuthenticatedAtelierClassMaterialsRoute:
    AuthenticatedAtelierClassMaterialsRoute,
  AuthenticatedAtelierFiringPricingRoute:
    AuthenticatedAtelierFiringPricingRoute,
  AuthenticatedAtelierKilnsRoute: AuthenticatedAtelierKilnsRoute,
  AuthenticatedAtelierPiecePricingRoute: AuthenticatedAtelierPiecePricingRoute,
  AuthenticatedAtelierRawMaterialsRoute: AuthenticatedAtelierRawMaterialsRoute,
  AuthenticatedAtelierRenovationRoute: AuthenticatedAtelierRenovationRoute,
  AuthenticatedAtelierStudentPaymentsRoute:
    AuthenticatedAtelierStudentPaymentsRoute,
  AuthenticatedAtelierStudentsRoute: AuthenticatedAtelierStudentsRoute,
  AuthenticatedAtelierWorkshopPricingRoute:
    AuthenticatedAtelierWorkshopPricingRoute,
  AuthenticatedSuperAdminCustomizationsRoute:
    AuthenticatedSuperAdminCustomizationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentInviteRoute: StudentInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
