/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomizationsRouteImport } from './routes/_authenticated/customizations'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedBudgetAnalysisRouteImport } from './routes/_authenticated/budget-analysis'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedSuperAdminCustomizationsRouteImport } from './routes/_authenticated/super-admin.customizations'
import { Route as AuthenticatedAtelierRawMaterialsRouteImport } from './routes/_authenticated/atelier.raw-materials'
import { Route as AuthenticatedAtelierClassMaterialsRouteImport } from './routes/_authenticated/atelier.class-materials'
import { Route as AuthenticatedAtelierCashFlowRouteImport } from './routes/_authenticated/atelier.cash-flow'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomizationsRoute =
  AuthenticatedCustomizationsRouteImport.update({
    id: '/customizations',
    path: '/customizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetAnalysisRoute =
  AuthenticatedBudgetAnalysisRouteImport.update({
    id: '/budget-analysis',
    path: '/budget-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminCustomizationsRoute =
  AuthenticatedSuperAdminCustomizationsRouteImport.update({
    id: '/super-admin/customizations',
    path: '/super-admin/customizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierRawMaterialsRoute =
  AuthenticatedAtelierRawMaterialsRouteImport.update({
    id: '/atelier/raw-materials',
    path: '/atelier/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierClassMaterialsRoute =
  AuthenticatedAtelierClassMaterialsRouteImport.update({
    id: '/atelier/class-materials',
    path: '/atelier/class-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtelierCashFlowRoute =
  AuthenticatedAtelierCashFlowRouteImport.update({
    id: '/atelier/cash-flow',
    path: '/atelier/cash-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/accounts': typeof AuthenticatedAccountsRoute
  '/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customizations': typeof AuthenticatedCustomizationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/accounts': typeof AuthenticatedAccountsRoute
  '/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customizations': typeof AuthenticatedCustomizationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/budget-analysis': typeof AuthenticatedBudgetAnalysisRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customizations': typeof AuthenticatedCustomizationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/atelier/cash-flow': typeof AuthenticatedAtelierCashFlowRoute
  '/_authenticated/atelier/class-materials': typeof AuthenticatedAtelierClassMaterialsRoute
  '/_authenticated/atelier/raw-materials': typeof AuthenticatedAtelierRawMaterialsRoute
  '/_authenticated/super-admin/customizations': typeof AuthenticatedSuperAdminCustomizationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/budget-analysis'
    | '/cards'
    | '/categories'
    | '/customizations'
    | '/dashboard'
    | '/import'
    | '/onboarding'
    | '/reconciliation'
    | '/settings'
    | '/transactions'
    | '/auth/callback'
    | '/atelier/cash-flow'
    | '/atelier/class-materials'
    | '/atelier/raw-materials'
    | '/super-admin/customizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/budget-analysis'
    | '/cards'
    | '/categories'
    | '/customizations'
    | '/dashboard'
    | '/import'
    | '/onboarding'
    | '/reconciliation'
    | '/settings'
    | '/transactions'
    | '/auth/callback'
    | '/atelier/cash-flow'
    | '/atelier/class-materials'
    | '/atelier/raw-materials'
    | '/super-admin/customizations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/budget-analysis'
    | '/_authenticated/cards'
    | '/_authenticated/categories'
    | '/_authenticated/customizations'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/onboarding'
    | '/_authenticated/reconciliation'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/auth/callback'
    | '/_authenticated/atelier/cash-flow'
    | '/_authenticated/atelier/class-materials'
    | '/_authenticated/atelier/raw-materials'
    | '/_authenticated/super-admin/customizations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customizations': {
      id: '/_authenticated/customizations'
      path: '/customizations'
      fullPath: '/customizations'
      preLoaderRoute: typeof AuthenticatedCustomizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget-analysis': {
      id: '/_authenticated/budget-analysis'
      path: '/budget-analysis'
      fullPath: '/budget-analysis'
      preLoaderRoute: typeof AuthenticatedBudgetAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/customizations': {
      id: '/_authenticated/super-admin/customizations'
      path: '/super-admin/customizations'
      fullPath: '/super-admin/customizations'
      preLoaderRoute: typeof AuthenticatedSuperAdminCustomizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/raw-materials': {
      id: '/_authenticated/atelier/raw-materials'
      path: '/atelier/raw-materials'
      fullPath: '/atelier/raw-materials'
      preLoaderRoute: typeof AuthenticatedAtelierRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/class-materials': {
      id: '/_authenticated/atelier/class-materials'
      path: '/atelier/class-materials'
      fullPath: '/atelier/class-materials'
      preLoaderRoute: typeof AuthenticatedAtelierClassMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier/cash-flow': {
      id: '/_authenticated/atelier/cash-flow'
      path: '/atelier/cash-flow'
      fullPath: '/atelier/cash-flow'
      preLoaderRoute: typeof AuthenticatedAtelierCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedBudgetAnalysisRoute: typeof AuthenticatedBudgetAnalysisRoute
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomizationsRoute: typeof AuthenticatedCustomizationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedAtelierCashFlowRoute: typeof AuthenticatedAtelierCashFlowRoute
  AuthenticatedAtelierClassMaterialsRoute: typeof AuthenticatedAtelierClassMaterialsRoute
  AuthenticatedAtelierRawMaterialsRoute: typeof AuthenticatedAtelierRawMaterialsRoute
  AuthenticatedSuperAdminCustomizationsRoute: typeof AuthenticatedSuperAdminCustomizationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedBudgetAnalysisRoute: AuthenticatedBudgetAnalysisRoute,
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomizationsRoute: AuthenticatedCustomizationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedAtelierCashFlowRoute: AuthenticatedAtelierCashFlowRoute,
  AuthenticatedAtelierClassMaterialsRoute:
    AuthenticatedAtelierClassMaterialsRoute,
  AuthenticatedAtelierRawMaterialsRoute: AuthenticatedAtelierRawMaterialsRoute,
  AuthenticatedSuperAdminCustomizationsRoute:
    AuthenticatedSuperAdminCustomizationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
