-- Store only the private object path on each piece. Signed URLs are generated by
-- the application when an authenticated workspace member opens the page.
ALTER TABLE public.class_materials_usage
  ADD COLUMN IF NOT EXISTS photo_path text;

COMMENT ON COLUMN public.class_materials_usage.photo_path IS
  'Private Storage object path for the class piece photo.';

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'class-piece-photos',
  'class-piece-photos',
  false,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Workspace members read class piece photos" ON storage.objects;
CREATE POLICY "Workspace members read class piece photos"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'class-piece-photos'
  AND public.is_workspace_member(((storage.foldername(name))[1])::uuid, auth.uid())
);

DROP POLICY IF EXISTS "Workspace members upload class piece photos" ON storage.objects;
CREATE POLICY "Workspace members upload class piece photos"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'class-piece-photos'
  AND public.is_workspace_member(((storage.foldername(name))[1])::uuid, auth.uid())
);

DROP POLICY IF EXISTS "Workspace members update class piece photos" ON storage.objects;
CREATE POLICY "Workspace members update class piece photos"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'class-piece-photos'
  AND public.is_workspace_member(((storage.foldername(name))[1])::uuid, auth.uid())
)
WITH CHECK (
  bucket_id = 'class-piece-photos'
  AND public.is_workspace_member(((storage.foldername(name))[1])::uuid, auth.uid())
);

DROP POLICY IF EXISTS "Workspace members delete class piece photos" ON storage.objects;
CREATE POLICY "Workspace members delete class piece photos"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'class-piece-photos'
  AND public.is_workspace_member(((storage.foldername(name))[1])::uuid, auth.uid())
);

NOTIFY pgrst, 'reload schema';
